name: deploy
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the latest code from the branch
        uses: actions/checkout@v3 
      
      - name: setup bun
        uses: oven-sh/setup-bun@v1 
      
      - name: install packages
        run: bun install 
      
      - name: build app
        run: bun run build:app 
      
      - name: set up ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh 
          chmod 600 ~/.ssh/id_rsa 

      - name: deploy to ruahman.net
        run: bun run deploy 

