name: deploy
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the latest code
        uses: actions/checkout@v3 
      
      - name: setup bun
        uses: oven-sh/setup-bun@v1 
      
      - name: install packages
        run: bun install 
      
      - name: build app
        run: bun run build:app 
      
      - name: scp to ruahman.net
        run: | 
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > __TEMP_INPUT_KEY_FILE
          chmod 600 __TEMP_INPUT_KEY_FILE
          scp -o StrictHostKeyChecking=no -i __TEMP_INPUT_KEY_FILE -P 22 -r ./packages/app/dist root@68.183.18.108:/var/www/wallet
