name: deploy-dev 
on:
  push:
    branches: [dev]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: oven-sh/setup-bun@v1 
      - run: bun install 
      - run: bun run build:app 
      - name: Set up known hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          echo "$KNOWN_HOSTS" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Run scp
        run: bun run deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        continue-on-error: true
