name: integrate

on:
  pull_request: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest  
    steps:
      - name: checkout the latest code from the branch
        uses: actions/checkout@v3 
      
      - name: setup bun
        uses: oven-sh/setup-bun@v1 
      
      - name: install packages
        run: bun install 

      - name: run tests
        run: bun run test
